using System;
using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;

namespace SplineMesh {
    /// <summary>
    /// Example of component to show the deformation of a mesh in a changing
    /// interval in spline space.
    /// 
    /// This component is only for demo purpose and is not intended to be used as-is.
    /// </summary>
    [ExecuteAlways]
    [RequireComponent(typeof(Spline))]
    public class HuaJuanContortAlong : MonoBehaviour {
        private Spline spline;
        private MeshBender meshBender;
        private float startPos = 0.0f;
        private float endPos = 0.0f;
        private float lastEndPos = 0.0f;

        [HideInInspector]
        public GameObject generated;

        public Mesh mesh;
        public Material material;
        public Vector3 rotation = Vector3.zero;
        public Vector3 scale = Vector3.one;
        public float meshLenth = 1.0f;
        [Range(0.0f, 1.0f)]
        public float range = 0.0f;

        private void OnEnable() 
        {
            spline = this.GetComponent<Spline>();
            Init();
        }
        private void OnValidate() 
        {
            spline = this.GetComponent<Spline>();
            Init();
        }
        private void Start()
        {
            startPos = Mathf.Lerp(0.0f, spline.Length - meshLenth * scale.x, range);
            lastEndPos = -1.0f;
        }
        private void Update() 
        {
            startPos = Mathf.Lerp(0.0f, spline.Length - meshLenth * scale.x, range);
            endPos = startPos + meshLenth * scale.x;
            if (endPos != lastEndPos && mesh != null && material != null)
            {
                Contort(startPos, endPos);
                lastEndPos = endPos;
            }
        }

        private void Contort(float start, float end) 
        {
            if (generated != null) {
                meshBender.Mode = MeshBender.FillingMode.StretchToInterval;
                meshBender.SetInterval(spline, start, end);
                meshBender.ComputeIfNeeded();                
            }
        }
        private void Init() 
        {
            string generatedName = "generated by " + GetType().Name;
            var generatedTranform = transform.Find(generatedName);
            generated = generatedTranform != null ? generatedTranform.gameObject : UOUtility.Create(generatedName, gameObject,
                typeof(MeshFilter),
                typeof(MeshRenderer),
                typeof(MeshBender));

            generated.GetComponent<MeshRenderer>().material = material;

            meshBender = generated.GetComponent<MeshBender>();
            spline = GetComponent<Spline>();

            meshBender.Source = SourceMesh.Build(mesh)
                .Rotate(Quaternion.Euler(rotation))
                .Scale(scale);
            meshBender.Mode = MeshBender.FillingMode.Once;
            meshBender.SetInterval(spline, 0);
        }
    }
}
